### ISSUE TITLE
Logs incorrect response upon user removal

### ISSUE THREAD

**Issue by gkeir** [Signiant/External-user-provisioning#1]
Papertrail
in the config.yaml file use an incorrect api key and try to remove a user. The logs,console and email report success but the user has not been removed.
For example:
papertrail:prod: ELaroche@signiant.com removed from papertrail.
The user was not actually removed.
Log, console and email should report errors on failure and success correctly preferably eluding to where the error is, for example an incorrect api key or an auth error or other.

**Comment by KseniaLL** [comment]
Fixed
