### ISSUE TITLE
Removal of user from Slack returns incorrect response

### ISSUE THREAD

**Issue by gkeir** [Signiant/External-user-provisioning#9]
Removing a user from Slack is actually an account deactivation, deletion does not appear possible. 
Once deactivated, a member's messages and files will still be accessible in Slack. This is to preserve the workspace's message history and to prevent confusion for other members

The result returned from the user provisioning tool is as follows:

Running remove: slack:prod  
username has NOT been removed, remove manually from the signiant-dev Slack team.

This should be more accurately represented to notify the tool user of what is actually happening, for example:

Running remove: slack:prod  
username has been deactivated.

**Comment by KseniaLL** [comment]
The issue is fixed
